<?php
namespace frontend\controllers;

use frontend\models\Address;
use frontend\models\LoginForm;
use frontend\models\Member;
use yii\web\Controller;

class ApiController extends Controller{
    public $enableCsrfValidation=false;     //防跨站攻击


   /* public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        return \Yii::$app->response->format=\yii\web\Response::FORMAT_JSON;     //设置返回的格式为JSON
    }*/

    /**
     * 用户注册
     * @return array
     */
    public function actionUserRegister(){
        //  username\password_hash\email\tel\captcha\checkcode
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'注册失败'
        ];
        if ($request->isPost){
            $model=new Member();
            $model->username=$request->post('username');
            $model->password_hash=\Yii::$app->security->generatePasswordHash($request->post('password_hash'));
            $model->email=$request->post('email');
            $model->tel=$request->post('tel');
            $model->checkcode=$request->post('checkcode');
            if ($model->validate()){
                $model->save();
                $result['error_code']=1;
                $result['data']=[
                    'id'=>$model->id,
                    'username'=>$model->username,
                    'email'=>$model->email,
                    'tel'=>$model->tel,
                ];
                $result['msg']='注册成功';
            }
            else{
                $result['msg']=$model->getErrors();
            }
        }else{
            $result['msg']='提交方式不合法';
        }
        return $result;
    }

    /**
     * 用户登录   username/password/checkcode/rememberMe
     * @return array
     */
    public function actionUserLogin(){
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'登录失败'
        ];
        if ($request->isPost){
            //先验证验证码
            $model=new LoginForm();
            $model->username=$request->post('username');
            $model->password=$request->post('password');
            $model->checkcode=$request->post('checkcode');
            //return $model->checkcode;die;
            $model->rememberMe=$request->post('rememberMe');
            if ($model->validate()){
                //验证用户名
                if ($model->check()=='true'){
                    $member=Member::findOne(['username'=>$model->username]);
                    $result['error_code']=1;
                    $result['data']=[
                        'id'=>$member->id,
                        'username'=>$member->username,
                        'auth_key'=>$member->auth_key,
                        'email'=>$member->email,
                        'tel'=>$member->tel,
                        'last_login_time'=>$member->last_login_time,
                        'last_login_ip'=>$member->last_login_ip,
                    ];
                    $result['msg']='登录成功';
                }elseif($model->check()==1){
                    $result['msg']='用户名不存在';
                }else{
                    $result['msg']='密码不正确';
                }
            }else{
                $result['msg']=$model->getErrors();
            }
        }else{
            $result['msg']='提交方式不合法';
        }
        return $result;
    }

    /**
     * 修改密码
     * @return array
     */
    public function actionEditPassword(){
        //      oldPwd/newPwd/confirmPwd
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'登录失败'
        ];
        if (\Yii::$app->user->identity){
            if ($request->isPost){
                $oldPwd=$request->post('oldPwd');
                $newPwd=$request->post('newpwd');
                $confirmPwd=$request->post('confirmPwd');
                if (isset($confirmPwd)){
                    if (isset($newPwd)){
                        if (isset($oldPwd)){
                            $member=Member::findOne(['id'=>\Yii::$app->user->identity->id]);
                            if (\Yii::$app->security->validatePassword($oldPwd,$member->password_hash)){
                                $result['error_code']=1;
                                $result['msg']='修改成功';
                            }else{
                                $result['msg']='旧密码密码不正确';
                            }
                        }else{
                            $result['msg']='旧密码不能为空';
                        }
                    }else{
                        $result['msg']='新密码不能为空';
                    }
                }else{
                    $result['msg']='确认密码不能为空';
                }
            }else{
                $result['msg']='提交方式不合法';
            }
        }else{
            $result['msg']='暂未登录';
        }
        return $result;
    }

    /**
     * 添加地址
     * @return array
     */
    public function actionAddAddress(){
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'保存失败'
        ];
        if (\Yii::$app->user->identity){
            if ($request->isPost){
                $model=new Address();
                $model->member_id=\Yii::$app->user->identity->id;
                $model->load($request->post(),'');
                $model->created_at=time();
                if ($model->validate()){
                    if ($model->is_default==1){
                        Address::updateAll(['is_default'=>0],['member_id'=>\Yii::$app->user->identity->id]);
                    }
                    $model->save();
                    $result['error_code']=1;
                    $result['data']=[
                         "id"=> $model->id,
                         "is_default"=> $model->is_default,
                         "name"=> $model->name,
                         "address"=>$model->address ,
                         "tel"=>$model->tel,
                         "cmbProvince"=>$model->cmbProvince,
                         "cmbCity"=>$model->cmbCity,
                         "cmbArea"=>$model->cmbArea,
                    ];
                    $result['msg']='保存成功';
                }else{
                    $result['msg']=$model->getErrors();
                }
            }else{
                $result['msg']='提交方式不合法';
            }
        }else{
            $result['msg']='暂未登录';
        }
        return $result;
    }

    /**
     * 修改地址
     * @return array
     */
    public function actionEditAddress(){
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'保存失败'
        ];
        if (\Yii::$app->user->identity){
            if ($request->isPost){
                $model=new Address();
                $model->member_id=\Yii::$app->user->identity->id;
                $model->load($request->post(),'');
                $model->created_at=time();
                if ($model->validate()){
                    if ($model->is_default==1){
                        Address::updateAll(['is_default'=>0],['member_id'=>\Yii::$app->user->identity->id]);
                    }
                    $model->save();
                    $result['error_code']=1;
                    $result['data']=[
                        "id"=> $model->id,
                        "is_default"=> $model->is_default,
                        "name"=> $model->name,
                        "address"=>$model->address ,
                        "tel"=>$model->tel,
                        "cmbProvince"=>$model->cmbProvince,
                        "cmbCity"=>$model->cmbCity,
                        "cmbArea"=>$model->cmbArea,
                    ];
                    $result['msg']='保存成功';
                }else{
                    $result['msg']=$model->getErrors();
                }
            }else{
                $result['msg']='提交方式不合法';
            }
        }else{
            $result['msg']='暂未登录';
        }
        return $result;
    }

    /**
     * 删除地址
     * @param $id
     * @param $member_id
     * @return array
     * @throws \Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelAddress($id, $member_id){
        $request=\Yii::$app->request;
        $result=[
            'error_code'=>0,
            'data'=>[],
            'msg'=>'保存失败'
        ];
        if ($request->isGet){
            $model=Address::findOne(['id'=>$id,'member_id'=>$member_id]);
            $model->delete();
            $result['error_code']=1;
            $result['data']=[
                'status'=>true
            ];
            $result['msg']='删除成功';
        }else{
            $result['msg']='请求方式错误';
        }
        return $result;
    }

    /**
     * @param $member_id
     * @return array
     */
    public function actionListAddress($member_id){
        $result=[
            'error_code'=>0,
            'data'=>'',
            'msg'=>'保存失败'
        ];
        if (\Yii::$app->user->identity){
            $rows=Address::find()->where(['member_id'=>$member_id])->all();
            $result['error_code']=1;
            $result['data']= $rows;
            $result['msg']='查询成功';
        }else{
            $result['msg']='暂未登录';
        }
        return $result;
    }

    /**
     * @return string
     */
    public function actionLogin(){
        return $this->render('login');
    }
}